### ISSUE TITLE
Create sub directories for grouping near duplicate images and move them to these directories

### ISSUE THREAD

**Issue by attard-andrew** [attard-andrew/project-oscar#9]

**Comment by truman-leung** [comment]
resolved

**Comment by attard-andrew** [comment]
This turned out to be pretty simple to solve. We used a for loop, with another for loop nested within it.

The first for loop basically goes over all of the keys stored in the database, assigns the key as the folder name, then using the current working directory, creates a folder using the assigned folder name.

Next, while still within the same loop (looking at one key in the available list), we create an array called fileList, which pulls all values assigned to the key currently being looped over - recalling that each key can have one or more images in its value array. It would look similar to:

![image](https://user-images.githubusercontent.com/54812701/70389522-ff0c5600-19f2-11ea-847a-a11da8c5b7f8.png)

Each image in that list is then looped over, and the shutil.copy() method is used to create a copy of each image within the new directory.
